### PR TITLE
Make the search sensitivity configurable

### PR DESCRIPTION
**Pull request by zaherg**
Added the `case-sensitive` option.

### CODE REVIEW

**Review by bbugh — CHANGES_REQUESTED** [review]
I hadn't been requested as a review so I didn't see it, sorry about that. 

It looks like the checks claim to be passing, but there are failure annotations in the diff: https://github.com/bbugh/action-fixme-check/pull/4/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Seems like something isn't working quite right.

**Comment by zaherg** [comment]
@bbugh I can't request a review unless I am a member (or contributor) this is why you didn't get any request.

> It looks like the checks claim to be passing, but there are failure annotations in the diff: https://github.com/bbugh/action-fixme-check/pull/4/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
> Seems like something isn't working quite right.

If I am not mistaken, they are passing because we have the `test` environment is set which prevent from exiting with an error status.

And the whole idea from the tests is to show the annotations in the files and the summary (correct me if I am wrong) whenever they find any of the terms in the code, which is exactly what happened here.

**Comment by bbugh** [comment]
@zaherg you're absolutely right. It's been so long since I set this up. Thank you for the effort, looks good!

**Review by bbugh — APPROVED** [review]

**Comment by bbugh** [comment]
Released in https://github.com/bbugh/action-fixme-check/releases/tag/v1.1.0

**Pull request merged**
